input_dir: ./MPD_dataset/MPD_events
output_dir: ./mpd_out/train_graphs
n_files: 100

selection:
    phi_slope_max: 0.01
    z0_max: 200
    pt_min: 0.25
    n_phi_sections: 2
    n_eta_sections: 1
    eta_range: [-5, 5]
    num_rows: 53
    rmax: 124.0
    zmax: 170.0