input_dir: ./TrackML_100_events
output_dir: ./trackml_out/train_graphs
n_files: 100

selection:
    phi_slope_max: 0.0006
    z0_max: 100
    n_phi_sections: 8
    n_eta_sections: 2
    eta_range: [-5, 5]
    remove_noise_fraction: 0