input_dir: ./MPD_dataset/MPD_events
output_dir: ./mpd_out/train_graphs
n_files: 10

selection:
    phi_slope_max: 0.01
    z0_max: 100
    pt_min: 0.5
    n_phi_sections: 4
    n_eta_sections: 1
    eta_range: [-5, 5]
    num_rows: 53