input_dir: ./MPD_dataset/MPD_events
output_dir: ./mpd_out/train_graphs
n_files: 1000

selection:
    phi_slope_max: 0.04
    z0_max: 400
    theta_max: 1.4
    d_min: 0
    d_max: 7
    pt_min: 0.2
    n_phi_sections: 1
    n_eta_sections: 1
    eta_range: [-10, 10]
    num_rows: 53
    rmax: 124.0
    zmax: 169.0