input_dir: ./MPD_dataset/MPD_events
output_dir: ./mpd_out/train_graphs
n_files: 100

selection:
    phi_slope_max: 0.005
    z0_max: 200
    theta_max: 1.3
    d_min: 0
    d_max: 4
    pt_min: 0.2
    n_phi_sections: 4
    n_eta_sections: 2
    eta_range: [-5, 5]
    num_rows: 53
    rmax: 124.0
    zmax: 170.0