input_dir: ./mpd_out/train_graphs
output_dir: ./mpd_out/train_logs
n_files: 1000
section_num: 4
test_size: 0.2
epoch_num: 1000
batch_size: 1
n_iters: 6
learning_rate: 0.001
step_size: 320
gamma: 0.97
pos_weight: 1
neg_weight: 1.1
time_lapse: 10